export const productsArray = [
  {
    id: '1',
    title:
      'Бавовняна футболка з написом "Кохай. Цілуй. Обіймай." T-shirt print 4802/60 black/feeling (чорний)',
    price: 599,
    image: ['/product2.jpeg', '/product2.jpeg', '/product2.jpeg'],
    vendorCode: 20001,
    category: 'homesuits',
    type: 'new',
    discount: 0,
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['blue', 'pink', 'white', 'black'],
  },
  {
    id: '2',
    title: 'Бавовняна футболка (білий)',
    price: 599,
    image: ['/product4.jpeg', '/product4.jpeg', '/product4.jpeg'],
    vendorCode: 20003,
    category: 'homesuits',
    type: 'top',
    discount: 10,
    size: ['M', 'L', 'XL', 'XXL'],
    color: ['pink', 'white', 'black'],
  },
  {
    id: '3',
    title:
      'Бавовняна футболка з написом "Кохай. Цілуй. Обіймай." T-shirt print 4802/60 black/feeling (чорний)',
    price: 599,
    image: ['/product2.jpeg', '/product2.jpeg', '/product2.jpeg'],
    vendorCode: 20003,
    category: 'homesuits',
    type: 'top',
    discount: 10,
    size: ['M', 'L', 'XL', 'XXL'],
    color: ['blue', 'white', 'black'],
  },
  {
    id: '4',
    title: 'Бавовняна футболка (білий)',
    price: 999,
    image: ['/product4.jpeg', '/product4.jpeg', '/product4.jpeg'],
    vendorCode: 20002,
    category: 'homesuits',
    type: 'new',
    discount: 0,
    size: ['S', 'M', 'L', 'XL'],
    color: ['blue', 'pink', 'black'],
  },
  {
    id: '5',
    title:
      'Бавовняна футболка з написом "Кохай. Цілуй. Обіймай." T-shirt print 4802/60 black/feeling (чорний)',
    price: 599,
    image: ['/product2.jpeg', '/product2.jpeg', '/product2.jpeg'],
    vendorCode: 20008,
    category: 'homesuits',
    type: 'top',
    discount: 25,
    size: ['L', 'XL', 'XXL'],
    color: ['blue', 'pink', 'white', 'black'],
  },
  {
    id: '6',
    title: 'Бавовняна футболка (білий)',
    price: 800,
    image: ['/product4.jpeg', '/product4.jpeg', '/product4.jpeg'],
    vendorCode: 20005,
    category: 'homesuits',
    type: 'new',
    discount: 0,
    size: ['M', 'L', 'XXL'],
    color: ['blue', 'pink', 'white'],
  },
  {
    id: '7',
    title:
      'Бавовняна футболка з написом "Кохай. Цілуй. Обіймай." T-shirt print 4802/60 black/feeling (чорний)',
    price: 599,
    image: ['/product2.jpeg', '/product2.jpeg', '/product2.jpeg'],
    vendorCode: 20009,
    category: 'homesuits',
    type: 'top',
    discount: 10,
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['blue', 'pink', 'white', 'black'],
  },
  {
    id: '8',
    title: 'Топ SEVILLA 7329/010 light  (білий)',
    price: 899,
    image: ['/product3.jpeg', '/product3.jpeg', '/product3.jpeg'],
    vendorCode: 20012,
    category: 'homesuits',
    type: 'sale',
    discount: 49,
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['blue', 'pink', 'white', 'black'],
  },
  {
    id: '9',
    title:
      'Бавовняна футболка з написом "Кохай. Цілуй. Обіймай." T-shirt print 4802/60 black/feeling (чорний)',
    price: 599,
    image: ['/product2.jpeg', '/product2.jpeg', '/product2.jpeg'],
    vendorCode: 20010,
    category: 'homesuits',
    type: 'top',
    discount: 34,
    size: ['S', 'M', 'L', 'XL'],
    color: ['blue', 'white', 'black'],
  },
  {
    id: '10',
    title: 'Топ SEVILLA 7329/010 light  (білий)',
    price: 999,
    image: ['/product3.jpeg', '/product3.jpeg', '/product3.jpeg'],
    vendorCode: 20013,
    category: 'homesuits',
    type: 'sale',
    discount: 34,
    size: ['S', 'L', 'XL'],
    color: ['blue', 'pink', 'white'],
  },
  {
    id: '11',
    title: 'Бавовняний халат SEVILLA 7329/010 light powder (рожевий)',
    price: 999,
    image: ['/product1.jpeg', '/product1.jpeg', '/product1.jpeg'],
    vendorCode: 20004,
    category: 'robes',
    type: 'sale',
    discount: 30,
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['pink', 'white', 'black'],
  },

  {
    id: '12',
    title: 'Бавовняний халат SEVILLA 7329/010 light powder (рожевий)',
    price: 800,
    image: ['/product5.jpeg', '/product5.jpeg', '/product5.jpeg'],
    vendorCode: 20006,
    category: 'robes',
    type: 'new',
    discount: 0,
    size: ['S', 'M', 'L', 'XL'],
    color: ['blue', 'pink', 'black'],
  },
  {
    id: '13',
    title: 'Бавовняний халат SEVILLA 7329/010 light powder (рожевий)',
    price: 999,
    image: ['/product1.jpeg', '/product1.jpeg', '/product1.jpeg'],
    vendorCode: 20007,
    category: 'robes',
    type: 'new',
    discount: 0,
    size: ['M', 'L', 'XL'],
    color: ['blue', 'pink', 'white'],
  },

  {
    id: '14',
    title: 'Бавовняний халат SEVILLA 7329/010 light powder (рожевий)',
    price: 500,
    image: ['/product5.jpeg', '/product5.jpeg', '/product5.jpeg'],
    vendorCode: 20011,
    category: 'robes',
    type: 'sale',
    discount: 34,
    size: ['M', 'L', 'XL', 'XXL'],
    color: ['blue', 'pink', 'white', 'black'],
  },

  {
    id: '15',
    title: 'Бавовняний халат SEVILLA 7329/010 light powder (рожевий)',
    price: 999,
    image: ['/product1.jpeg', '/product1.jpeg', '/product1.jpeg'],
    vendorCode: 20013,
    category: 'robes',
    type: 'top',
    discount: 34,
    size: ['S', 'M', 'L', 'XL'],
    color: ['blue', 'pink', 'white'],
  },
  {
    id: '16',
    title: 'Топ SEVILLA 7329/010 light  (білий)',
    price: 999,
    image: ['/product3.jpeg', '/product3.jpeg', '/product3.jpeg'],
    vendorCode: 20013,
    category: 'pajamas',
    type: 'sale',
    discount: 34,
    size: ['S', 'L', 'XL'],
    color: ['blue', 'pink', 'white'],
  },
  {
    id: '17',
    title: 'Топ SEVILLA 7329/010 light  (білий)',
    price: 999,
    image: ['/product3.jpeg', '/product3.jpeg', '/product3.jpeg'],
    vendorCode: 20013,
    category: 'nightshirts',
    type: 'sale',
    discount: 34,
    size: ['S', 'L', 'XL'],
    color: ['blue', 'pink', 'white'],
  },
  {
    id: '18',
    title: 'Топ SEVILLA 7329/010 light  (білий)',
    price: 999,
    image: ['/product3.jpeg', '/product3.jpeg', '/product3.jpeg'],
    vendorCode: 20013,
    category: 'sweatshirts',
    type: 'sale',
    discount: 34,
    size: ['S', 'L', 'XL'],
    color: ['blue', 'pink', 'white'],
  },
  {
    id: '19',
    title: 'Топ SEVILLA 7329/010 light  (білий)',
    price: 999,
    image: ['/product3.jpeg', '/product3.jpeg', '/product3.jpeg'],
    vendorCode: 20013,
    category: 'pantsandleggings',
    type: 'sale',
    discount: 34,
    size: ['S', 'L', 'XL'],
    color: ['blue', 'pink', 'white'],
  },
]

export const slider = ['/slide1.jpeg', '/slide1.jpeg', '/slide1.jpeg']

export const menu = [
  {
    name: 'Піжами',
    link: '/pajamas',
  },
  {
    name: 'Нічні сорочки',
    link: '/nightshirts',
  },
  {
    name: 'Халати',
    link: '/robes',
  },
  {
    name: 'Домашні костюми',
    link: '/homesuits',
  },
  {
    name: 'Світшоти',
    link: '/sweatshirts',
  },
  {
    name: 'Штани та легінси',
    link: '/pantsandleggings',
  },
]
