import type { Metadata } from "next";
import { Raleway, Arima } from "next/font/google";

import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });
const arial = Arima({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
